version: '3'

services:
  api:
    container_name: bookstore_api
    build: 
      context: .
      target: dev
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - pg_db
    command: npm run preparestart
  pg_db:
    image: postgres:latest
    container_name: bookstore_db
    environment:
      POSTGRES_DB: books-db
      POSTGRES_USER: books
      POSTGRES_PASSWORD: bookspwd
    ports:
      - "5432:5432"
    volumes:
      - pg_db:/var/lib/postgresql/data
volumes:
  pg_db: